spring:
  output:
      ansi:
        enabled: ALWAYS
  devtools:
    livereload:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:test"
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
management:
  security:
    enabled: false
#  security:
#    name: user
#    password: password
#    role: USER


---
spring:
  profiles: production
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver

