spring:
  datasource:
    url: "jdbc:h2:mem:test"
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
  security:
    name: user
    password: password
    role: USER

---
spring:
  profiles: production
  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver

